php-version = "8.2"

[source]
paths = [
  "src",
  # "tests/",
  # "importmap.php",
  # "migrations/",
]
includes = ["vendor"]
excludes = ["src/Kernel.php", "src/DataFixtures"]

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["phpunit", "symfony"]

[linter.rules]
ambiguous-function-call = { enabled = true }
literal-named-argument = { enabled = true }
halstead = { effort-threshold = 7000 }
too-many-methods = { enabled = true, threshold = 25 }
no-boolean-flag-parameter = { enabled = true }
no-else-clause = { enabled = true }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = true
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true

[guard]
mode = "default"

[guard.perimeter]
# Defines the architectural layers from core to infrastructure.
layering = [
    "App\\Domain",
    "App\\Infrastructure",
    "App\\DataFixtures",
    "App\\Tests"
]

# Creates reusable aliases for groups of namespaces.
[guard.perimeter.layers]
core = ["@native", "Psl\\**"]
framework = ["Symfony\\**"]
doctrine = ["Doctrine\\**"]
libs = ["Twig\\**", "Sonata\\**", "Gedmo\\**"]

[[guard.perimeter.rules]]
namespace = "App\\Domain"
permit = [ "@layer:framework", "@layer:core","@layer:doctrine"]

[[guard.perimeter.rules]]
namespace = "App\\Infrastructure"
permit = ["@native","@layer:framework","@layer:libs","@layer:doctrine"]

[[guard.perimeter.rules]]
namespace = "App\\Tests"
permit = ["@all"]

[[guard.perimeter.rules]]
namespace = "App\\DataFixtures"
permit = ["@all"]

[[guard.structural.rules]]
on               = "App\\Infrastructure\\Controller\\**"
target           = "class"
must-be-named    = "*Controller"
must-be-final    = true
reason           = "Controllers must be final and follow naming conventions."

[[guard.structural.rules]]
on          = "App\\Domain\\**\\Enum\\**"
must-be     = ["enum"]
reason      = "This namespace is designated for enums only."
